services:
  web:
    build:
      context: .
      dockerfile: docker/prod/Dockerfile
    environment:
      DJANGO_SETTINGS_MODULE: blog.settings.prod
    volumes:
      - static_volume:/app/staticfiles
      - ./blog:/app
    expose:
      - 8000
    depends_on:
      db:
        condition: service_healthy

  nginx:
    image: nginx:latest
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
      - /etc/letsencrypt:/etc/letsencrypt:ro
      - ./docker/nginx/html:/usr/share/nginx/html
      - static_volume:/app/staticfiles
    depends_on:
      - web

  db:
    image: postgres:16
    environment:
      POSTGRES_DB: mydatabase
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD", "pg_isready", "-d", "mydatabase", "-U", "user"]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  postgres_data:
    external: true
  static_volume:
