services:
  web:
    build:
      context: .
      dockerfile: docker/dev/Dockerfile
    environment:
      DJANGO_SETTINGS_MODULE: backend.settings.dev
    env_file:
      - .env.dev
    volumes:
      - ./backend:/app
    ports:
      - "8000:8000"
    depends_on:
      - db

  db:
    image: postgis/postgis:17-3.5
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - .env.dev
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD", "pg_isready", "-d", "mydatabase", "-U", "user"]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  postgres_data:
    external: true