services:
  web:
    build:
      context: .
      dockerfile: docker/prod/Dockerfile
    environment:
      DJANGO_SETTINGS_MODULE: backend.settings.prod
    volumes:
      - ./backend:/app
    expose:
      - 8000
    depends_on:
      db:
        condition: service_healthy

  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    environment:
      POSTGRES_DB: mydatabase
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    volumes:
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./docker/nginx/html:/usr/share/nginx/html
    depends_on:
      - web

  db:
    image: postgis/postgis:17-3.5
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD", "pg_isready", "-d", "mydatabase", "-U", "user"]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  postgres_data:
