# Generated by Django 5.2.6 on 2025-09-15 14:41

import ckeditor.fields
import core.utils
import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, unique=True)),
                ('slug', models.SlugField(blank=True, editable=False, max_length=25, unique=True)),
            ],
            options={
                'verbose_name': 'Category',
                'verbose_name_plural': 'Categories',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, validators=[django.core.validators.MinLengthValidator(5, 'Title must be at least 5 characters long.')])),
                ('slug', models.SlugField(blank=True, editable=False, max_length=265, unique=True)),
                ('content', ckeditor.fields.RichTextField(validators=[django.core.validators.MinLengthValidator(50, 'Content must be at least 50 characters long.')])),
                ('thumbnail', models.ImageField(blank=True, help_text='Upload a thumbnail image for this article (recommended: 1200x630px)', null=True, upload_to=core.utils.article_thumbnail_path)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('published', models.BooleanField(default=False)),
                ('published_at', models.DateTimeField(blank=True, editable=False, null=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='articles', to=settings.AUTH_USER_MODEL)),
                ('categories', models.ManyToManyField(blank=True, related_name='articles', to='core.category')),
            ],
            options={
                'ordering': ['-created_at'],
                'permissions': [('can_publish', 'Can publish articles')],
            },
        ),
        migrations.CreateModel(
            name='ArticleView',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_ip', models.CharField(max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.article')),
            ],
            options={
                'indexes': [models.Index(fields=['article', 'user_ip', 'created_at'], name='core_articl_article_60514a_idx')],
                'unique_together': {('article', 'user_ip', 'created_at')},
            },
        ),
        migrations.AddIndex(
            model_name='article',
            index=models.Index(fields=['-created_at'], name='core_articl_created_f70927_idx'),
        ),
        migrations.AddIndex(
            model_name='article',
            index=models.Index(fields=['published'], name='core_articl_publish_e5ba0f_idx'),
        ),
    ]
