# Generated by Django 5.2.6 on 2025-09-05 09:56

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('slug', models.SlugField(blank=True, max_length=100, unique=True)),
            ],
            options={
                'verbose_name': 'Category',
                'verbose_name_plural': 'Categories',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, validators=[django.core.validators.MinLengthValidator(5, 'Title must be at least 5 characters long.')])),
                ('slug', models.SlugField(blank=True, max_length=200, unique=True)),
                ('content', models.TextField(validators=[django.core.validators.MinLengthValidator(50, 'Content must be at least 50 characters long.')])),
                ('excerpt', models.TextField(blank=True, help_text='Brief summary of the article (max 300 characters)', max_length=300)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('published', models.BooleanField(default=False)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('featured', models.BooleanField(default=False, help_text='Feature this article on the homepage')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='articles', to=settings.AUTH_USER_MODEL)),
                ('categories', models.ManyToManyField(blank=True, related_name='articles', to='core.category')),
                ('tags', models.ManyToManyField(blank=True, related_name='articles', to='core.tag')),
            ],
            options={
                'ordering': ['-created_at'],
                'permissions': [('can_publish', 'Can publish articles'), ('can_feature', 'Can feature articles')],
                'indexes': [models.Index(fields=['-created_at'], name='core_articl_created_f70927_idx'), models.Index(fields=['published'], name='core_articl_publish_e5ba0f_idx'), models.Index(fields=['featured'], name='core_articl_feature_1f38dd_idx')],
            },
        ),
    ]
