# Generated by Django 5.2.6 on 2025-09-17 12:48

import core.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_article_content_alter_article_title_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='thumbnail',
            field=models.ImageField(blank=True, help_text='Upload a thumbnail image for this article (recommended: 1200x630px)', max_length=500, null=True, upload_to=core.utils.article_thumbnail_path),
        ),
    ]
