# Generated by Django 5.2.6 on 2025-09-05 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_remove_article_tags_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='thumbnail',
            field=models.ImageField(blank=True, help_text='Upload a thumbnail image for this article (recommended: 1200x630px)', null=True, upload_to='articles/thumbnails'),
        ),
    ]
