# Generated by Django 5.2.6 on 2025-09-07 12:59

import core.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_article_thumbnail'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='article',
            options={'ordering': ['-created_at'], 'permissions': [('can_publish', 'Can publish articles')]},
        ),
        migrations.AlterField(
            model_name='article',
            name='thumbnail',
            field=models.ImageField(blank=True, help_text='Upload a thumbnail image for this article (recommended: 1200x630px)', null=True, upload_to=core.utils.article_thumbnail_path),
        ),
    ]
