# Generated by Django 5.2.6 on 2025-09-11 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_articleview'),
    ]

    operations = [
        migrations.AddField(
            model_name='articleview',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddIndex(
            model_name='articleview',
            index=models.Index(fields=['article', 'user_ip', 'created_at'], name='core_articl_article_60514a_idx'),
        ),
    ]
