# Generated by Django 5.2.6 on 2025-09-12 13:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_articleview_created_at_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='articleview',
            unique_together={('article', 'user_ip', 'created_at')},
        ),
    ]
