# Generated by Django 5.2.6 on 2025-09-15 00:19

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_alter_articleview_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='slug',
            field=models.SlugField(blank=True, editable=False, max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='article',
            name='title',
            field=models.CharField(max_length=255, validators=[django.core.validators.MinLengthValidator(5, 'Title must be at least 5 characters long.')]),
        ),
    ]
